version: "2"

run:
  timeout: 3m
  tests: false

formatters:
  enable:
    - goimports

linters:
  enable:
    - cyclop
    - errname
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godot
    - gosec
    - lll
    - loggercheck
    - makezero
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - predeclared
    - reassign
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    errcheck:
      check-type-assertions: true

    exhaustive:
      check:
        - switch
        - map

    funlen:
      lines: 150
      statements: 80

    gocognit:
      min-complexity: 25

    gosec:
      excludes:
        - G204
        - G304

    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true

    nakedret:
      max-func-lines: 10

    lll:
      line-length: 180

  exclusions:
    paths:
      - tests